title: Alanwu's Blog
owner: alanwu-9582
description: NTUT ETUHP
language: zh-TW
timeZone: +0800
timeFormat: '%Y/%m/%d'
siteUrl: https://alanwu-9582.github.io/Alanwu9582-blog

twitter:
  site: '@XxAlanXDxX'
  creator: '@XxAlanXDxX'
# ! liker:
# ! account: likerAccount

iconPath: 
  ico: image/configImage/icon.ico
  png: image/configImage/avatar.png

avatarPath: image/configImage/avatar.png

badges:
  - icon: 🪛
    message: FRC8725 Software Coach
  - icon: 👨‍💻
    message: UWU
  - icon: 👻
    message: :P

tabs:
  home: 
    text: Home
  about:
    text: About
    path: about.md
  articles: 
    text: Articles
  portfolio: 
    text: Portfolio
tabsAmount: 4

switches:
  rssUrl: 
    text: Copy RSS
  backgroundMusic:
    text: BG Music
    path: audio/relax.wav
    volume: 0.5
  darkMode: 
    text: Dark Mode
switchesAmount: 3

pages: 
  filter:
    text: Filter
    search: Search
    archives: Archives
    categories: Categories
    tags: Tags
  outline:
    text: Outline

category:
  - name: Hacking
    color:
      bright: '75, 200, 168'
      dark: '61, 162, 136'
    
# skinPath: image/configImage/grandmaster8787_mcskin.png